### PR TITLE
Gallery

### PR DESCRIPTION
**Pull request by mpmdean**
@shenmidelin I'd like to start migrating our examples into a sphinx gallery in order to help users read use them more freely. Please can you check the attached? 

@mrakitin  Could you look to see that I haven't done anything stupid in terms of the way repo structure?

### CODE REVIEW

**Comment by mrakitin** [comment]
I like the resulted example at https://nsls-ii.github.io/edrixs/auto_examples/example_0_ed_calculator.html#sphx-glr-auto-examples-example-0-ed-calculator-py!

**Comment by mpmdean** [comment]
Thanks @mrakitin . One major thing, I never understood in https://github.com/NSLS-II/edrixs/blob/master/examples/sphinx/example_0_ed_calculator.py (see the end)
was how to include 
`sphinx_gallery_thumbnail_path = '_static/calculator.jpg`

as a comment that is not rendered as rst

I thought the empty space before the line would do this
https://sphinx-gallery.github.io/stable/syntax.html#embedding-rst
but it seems not

**Comment by mrakitin** [comment]
That's a good question, @mpmdean. I haven't experimented with the custom thumbnails myself, and was always relying on the matplotlib figures generated by examples. It's worth to look into anyway.

**Comment by mpmdean** [comment]
Hi @mrakitin providing the link seems to be working fine. What I don't understand is why it appears rendered in the final webpage. It should be an unrendered comment, which is mean to be denoted by  the space I included ahead of the line in question. Is this something that you can help with?

**Pull request merged**
