### PR TITLE
update docker commands

### PR DESCRIPTION
**Pull request by mpmdean**
A small update is needed. 

I'm pointing this towards my docker build now. I would like to see the autobuild working, although it looks like it might not as it's been going a couple of hours?

### CODE REVIEW

**Comment by shenmidelin** [comment]
For the first time, it will build from the first command in the Dockerfile, so it will takes 1-2 hours to install all the libraries (first and second RUN command in Dockerfile). The most time-consuming is compile openmpi, openblas from source. It will use cache based on the layer structure (each command is a layer) in later buildings, so it will be fast if we only change the contents in last two commands (COPY and RUN).

**Comment by mpmdean** [comment]
Yes, I see that autobuildng are working in both our dockhubs. I think we should probably point to yours? And I guess I can switch mine off?

**Comment by mrakitin** [comment]
That's a good idea in general. However, why not to use apt packages for the heavy dependencies?

Another idea: a separate image can be used to build all hard-dependencies, which can be built once (or very rarely), and then can be used as a base image for the frequently changing.

**Comment by shenmidelin** [comment]
apt packages of openmpi sometimes cause running problems, so I prefer to compile one from source.

It's a great idea to build a separate base image to include all the hard-dependencies. I will do that.

**Pull request merged**
