### PR TITLE
Change BSD to GPL license 

### LINKED ISSUE #7: GPL License
@NSLS-II/edrixs-team , Hi all, the paper of edrixs code (https://arxiv.org/pdf/1812.05735.pdf) 
 has been accepted as publication in CPC, I am now modifying it to submit a second version. The original version is based on the repo on my account, so I want to modify it based on the new repo under NSLS-II.  One issue is the license, GPL license is required for the codes developed in the COMSCOPE center (https://www.bnl.gov/comscope/software/index.php), so could we still use GPL license for projects under NSLS-II ?

### PR DESCRIPTION
**Pull request by shenmidelin**
I have changed the license from BSD to GPL.

----
Updated by @mrakitin: closes #7.

### CODE REVIEW

**Comment by tacaswell** [comment]
This repo is new enough and getting licenses wrong is a big enough issue I am half advocating for re-writing history to correct the record.

**Comment by mpmdean** [comment]
One might revisit the structure of the cookiecutter regarding this issue? e.g. putting instructions to copy a license?

**Comment by mrakitin** [comment]
Good idea @mpmdean.

@tacaswell, how can it be achieved? A total squashing of all the commits in 1?

**Comment by tacaswell** [comment]
I would do an interactive rebase to squash this commit into the first one.

**Pull request merged**
