### PR TITLE
Create a base docker image

### PR DESCRIPTION
**Pull request by shenmidelin**
I move the `Dockerfile` to a sub-folder `docker/`,  and add a `Dockerfile_base` to build a base image `edrixs/edrixs_base`. 

To create the base image
`docker build -t edrixs/edrixs_base -f docker/Dockerfile_base https://github.com/NSLS-II/edrixs.git#master`

To create the edrixs image
`docker build -t edrixs/edrixs -f docker/Dockerfile https://github.com/NSLS-II/edrixs.git#master`

Is this OK?

### CODE REVIEW

**Comment by mpmdean** [comment]
Can we add ipympl to the base image

https://github.com/matplotlib/jupyter-matplotlib

I think this requires
```
pip install ipympl
```

installing via here nodejs: https://nodejs.org/en/download/
and then

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib
```

**Comment by shenmidelin** [comment]
Install this package will install a lot of dependences, which will increase the image size a lot (about 0.6G), the result is:

before installing,

`du -smh /usr`   1.1G

after installing 

`du -smh /usr`   1.7G

I think we need to keep the size of the image not too large. If the user really want to use it, they can install by themselves after launching the container.

**Comment by mpmdean** [comment]
How about we (you :)) make another dockerfile
docker/Dockerfile_interactive
which has ipympl as above 

and I build that in my dockerhub account?

That we the official tag remains similarly simple and small, but I maintain easy access to the packages I want?

**Comment by shenmidelin** [comment]
That will be a good choice, let's maintain a simple and small version for basic usage, and design some ones with more features.

**Comment by shenmidelin** [comment]
How about this?
In Dockerfile_interactive file, we use `FROM edrixs/edrixs` and add one more `RUN` command to install additional packages.

**Comment by shenmidelin** [comment]
@mpmdean  I have built a test one for edrixs_interactive, you can test it to see whether it can work.

`docker pull edrixs/edrixs_interactive`

**Comment by mpmdean** [comment]
edrixs/edrixs_interactive works nicely!

**Pull request merged**
