### PR TITLE
add instructions for python usage

### PR DESCRIPTION
**Pull request by mpmdean**
This is extra documentation (written in response to the conversation with the Yale folks). I think they are finding it hard to inspect the output in detail. Especially if they are adding print statements in the source code.

### CODE REVIEW

**Comment by mpmdean** [comment]
@mrakitin @shenmidelin 

I'm not sure where the build error is coming from. Presumably not this PR. I notice some linter errors in the report. Is this the only problem. Either way, it would be good to fix this.

**Comment by shenmidelin** [comment]
@mpmdean I found this building error since PR #44 . It is related to codecov, the errors are:

```
Processing gcov (disable by -X gcov)
    Executing gcov (['find', '/home/travis/build/NSLS-II/edrixs', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+'])
    Error running `['find', '/home/travis/build/NSLS-II/edrixs', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+']`: Command '['find', '/home/travis/build/NSLS-II/edrixs', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+']' returned non-zero exit status 1.
```

I don't know how to fix that. @mrakitin Could you help us to take a look at this issue?

**Comment by mpmdean** [comment]
@shenmidelin @mrakitin  if the build error is unrelated we can solve that in another PR

**Comment by shenmidelin** [comment]
@mpmdean @mrakitin  This issue is actually due to the new version of the python codestyle that ambiguous variable name `l` is not allowed. I have solved this issue by PR #47.

**Comment by mpmdean** [comment]
I was expecting the online docs to update when this was merged, but they still look the same to me.

**Comment by shenmidelin** [comment]
We should first merge PR #47 to fix the flake8, then the travis can continue to update the online doc.

**Pull request merged**
