### PR TITLE
revised version of ex2

### PR DESCRIPTION
**Pull request by mpmdean**
This supersedes #67 which I will close

- [ ] Is there a better way to set the valance energy and be able to use different doed?
- [ ] There seems to be an issue with CF on bath vs on impurity?
- [ ] Can we improve the notation for the equations for the energies of the states `d^8L^10` can be confusing maybe `d^8b^10`. See comments by @jwfreeland. @shenmidelin Suggests `L` it is reasonably clear in view of `\underline{U}` being used for holes and `L^10` being used for electrons.
- [ ] Why is there Hz =  0.120 in quanty?
- [ ] How to calculate alpha d8 beta d9L representation

### CODE REVIEW

**Comment by shenmidelin** [comment]
I have fixed several bugs and modified some parameters. Now, the XAS results are same as that in Quanty's example.

- I don't know whether there is a better way for defining the charge-transfer energy.

- The issue with CF is due to wrong way to add a diagonal matrix, see f984786

- No problem of `L^n`

- The external field due to the anti-ferromagnetic order is Hz=0.12 in Quanty 

- Examine the wave functions of the ground states can give the alpha and beta, but I need to modify the Fortran code to output those informations. However, this type of calculation at nd=8 is very cheap, so the easiest way to do this is to write a pure python code.

**Comment by jwfreeland** [comment]
@shenmidelin Yilin I tried running the new example but ran into an issue with E_d, E_L = edrixs.CT_imp_bath(U_dd, Delta, nd). It says CT_imp_bath is not defined. I did a pull to update my edrixs but did not seem to fix it. Suggestions?

**Comment by mpmdean** [comment]
Hi @jwfreeland 
Are you using the docker version?

**Comment by jwfreeland** [comment]
I am using the docker version so I did docker pull edrixs/edirxs.

**Comment by jwfreeland** [comment]
Then I am running in jupyter using interactive mode

**Comment by jwfreeland** [comment]
Realized I should clarify. I opened a terminal in the jupyter docker interactive session and did python example...py

**Comment by mpmdean** [comment]
@jwfreeland 

Usually one would use the edrixs/edrixs_interactive container to launch Jupyter.
https://nsls-ii.github.io/edrixs/user/usedocker.html#connect-to-docker-python-session-with-jupyter

Let's confirm you indeed have the latest versions
`docker pull edrixs/edrixs`
should day Digest
 `sha256:81efb49258c850dd8e7733f1b3989e6a6c6b5a205734994f287a21a6fb6ddf35`

`docker pull edrixs/edrixs`
should day Digest
`sha256:bea9da6e0985e91f78550ce114385445cd89fc78f8c93db345c236a7a509f5bd`

**Comment by jwfreeland** [comment]
@mpmdean Yes all those check and I am running in the interactive mode with docker using:

docker run -it -p 8888:8888 -u rixs -w /home/rixs -v /Users/jfreeland/Applications/edrixs:/home/rixs/data edrixs/edrixs_interactive

I tried via a notebook that works for the edrixs calculation and does not seem to get those routines either.  I will keep poking.

**Comment by mpmdean** [comment]
@jwfreeland 

I can reproduce the issue. It looks like you have the latest docker image, but our recent pushes have not auto built for some reason.

**Pull request merged**
