### PR TITLE
RIXS example

### PR DESCRIPTION
**Pull request by mpmdean**
Update the docs to include a example for an atomic RIXS calculation.

### CODE REVIEW

**Comment by mpmdean** [comment]
This is a rendering of the example to aid review

[RIXS calculations for an atomic model — edrixs documentation.pdf](https://github.com/NSLS-II/edrixs/files/6712574/RIXS.calculations.for.an.atomic.model.edrixs.documentation.pdf)

**Comment by mpmdean** [comment]
@mrakitin It seems this failed to update the docs. Can you check what's going on? I'm a bit stumped.

**Comment by mrakitin** [comment]
I guess we need a workflow that would publish to nsls-ii.github.io similarly to https://github.com/bluesky/bluesky/blob/ebffcc55c7d28e279ce101cb79ea1ff4a3d92411/.github/workflows/publish-docs.yml#L49-L60.

@danielballan, what would be your suggestion about it? I believe we haven't set up secrets for nsls-ii.github.io, only for blueskyproject.io, right?

**Comment by danielballan** [comment]
Yes, it's not clear to me what `nsls-ii.github.io` should be _for_ anymore. It's possible we want to move this to a `bnl.gov` domain and set up redirects on `nsls-ii.github.io`. That's why I haven't set up secrets for it yet.

**Comment by danielballan** [comment]
Actually, it looks like I _did_ set up secrets for it. There is a secret named `ACTIONS_DOCUMENTATION_DEPLOY_KEY` set up on this (NSLS-II) organization. So, yes, you need to follow something like [what @mrakitin linked above](https://github.com/bluesky/bluesky/blob/ebffcc55c7d28e279ce101cb79ea1ff4a3d92411/.github/workflows/publishdocs.yml#L49-L60). Please ask for careful review, but with that secret you have the potential to overwrite/break _all_ of `nsls-ii.github.io/` so it must be configured carefully.

**Comment by mpmdean** [comment]
Thanks @danielballan 

@mrakitin Would you be able to help with this? If it would be helpful I could try to get a PR started, but I think I'd have a very hard time completing the whole thing.

**Comment by mpmdean** [comment]
@mrakitin and @danielballan 

Might it be possible to address this in the coming days?

**Comment by mrakitin** [comment]
Done via #125.

**Pull request merged**
