### PR TITLE
DOC: Fix automodule usage.

### PR DESCRIPTION
**Pull request by danielballan**
Counter-proposal to #4, which I suggest you revert. Relative imports are useful
and should be OK --- the problem here is sphinx.

This was a very confusing sphinx error. It turns out that shpinx tries to
import the module as a standalone file without realizing that it is part of a
larger package, and relative imports break. This change sets sphinx right.

### CODE REVIEW

**Comment by mpmdean** [comment]
I reverted #4 and will leave this to the experts.

**Comment by danielballan** [comment]
Ha. If _only_ I weren't a sphinx expert.... :- D

**Comment by mrakitin** [comment]
The codecov fix in 7d9b944 was copied over from https://github.com/NSLS-II/bluesky/pull/1156/files.

**Comment by mrakitin** [comment]
Neat, it passed now.

**Comment by mrakitin** [comment]
The docs are live now: https://nsls-ii.github.io/edrixs (they are only uploaded when the PR is merged, i.e. from the master branch).

**Comment by mpmdean** [comment]
Thanks guys

**Pull request merged**
