### PR TITLE
add Cu d10p5 state

### PR DESCRIPTION
**Pull request by mpmdean**
This is my attempt to add the atomic parameters for Cu d10p5. I took these from crispy in the screenshot since the wrapper for Cowan's code that I use 
https://github.com/mretegan/atomic-parameters
did not return Slater parameters. 

I worry a bit that I'm doing something stupid? 

Screen Shot 2020-09-01 at 1 47 27 PM

### CODE REVIEW

**Comment by mretegan** [comment]
@mpmdean 
The parameters in Crispy are correct (btw the ones from the screenshot are for 2p5 3d9). The problem is with the atomic-parameters code, more precisely the integrals are not printed in the part of the RCN output parsed by the Python code.

Below is part of the RCN output that prints the Slater integrals (for the same electronic configuration):

```
 ( 2P, 3D)       0    3.1653147 RYD  =     43.06664  EV    1.000         1    0.4932837 RYD  =      6.71152  EV    1.000
 ( 2P, 3D)       2    0.6465618 RYD  =      8.79699  EV    1.000         3    0.2807299 RYD  =      3.81955  EV    1.000

...

 ( 3D, 3D)       0    2.2921536 RYD  =     31.18658  EV    1.000         0    0.0000000 RYD  =      0.00000  EV    0.000
 ( 3D, 3D)       2    1.0743782 RYD  =     14.61777  EV    1.000         0    0.0000000 RYD  =      0.00000  EV    0.000
 ( 3D, 3D)       4    0.6710889 RYD  =      9.13070  EV    1.000         0    0.0000000 RYD  =      0.00000  EV    0.000
```

I guess I have to re-write the parser (sigh).

**Comment by mpmdean** [comment]
Thanks @mretegan 

I was messing around and attached the wrong screenshot. I think this means the code update has been done correctly. 

@shenmidelin maybe you can check too?

Screen Shot 2020-09-01 at 4 35 38 PM

**Comment by shenmidelin** [comment]
@mpmdean  I thought that F2, F4 will not play roles in d9 and d10 configurations. In Cu.json file, I remembered that I have gave some default values for 3d10 2p5 configuration.

**Comment by mpmdean** [comment]
Hi @shenmidelin from what I can see we currently do not have any values for Cu d10p5 and if I do

```
import edrixs
res = edrixs.get_atom_data('Cu', v_name='3d', v_noccu=9, edge='L3')
```

We can an Exception and not default values.  

```
Exception                                 Traceback (most recent call last)
<ipython-input-2-d26eb2f5f571> in <module>
      3 import matplotlib as mpl
      4 import edrixs
----> 5 res = edrixs.get_atom_data('Cu', v_name='3d', v_noccu=9, edge='L3')
      6 res

~/data/edrixs/edrixs/utils.py in get_atom_data(atom, v_name, v_noccu, edge, trans_to_which, label)
    890                         edge_name[0:2] + str(c_norb[edge_name[1]]-1))
    891         if case not in atom_dict:
--> 892             raise Exception("This configuration is currently not available in atom_data", case)
    893 
    894         nslat = len(slater_name)

Exception: ('This configuration is currently not available in atom_data', '3d10_2p5')
```

**Comment by mpmdean** [comment]
This PR produces the following. 

```
noccu = 9
res = edrixs.get_atom_data('Cu', v_name='3d', v_noccu=noccu, edge='L3')
res

{'slater_i': [('F0_11', 0.0), ('F2_11', 13.886), ('F4_11', 8.67)],
 'v_soc_i': [0.102],
 'slater_n': [('F0_11', 0.0),
  ('F2_11', 13.612),
  ('F4_11', 8.458),
  ('F0_12', 0.0),
  ('F2_12', 8.178),
  ('G1_12', 6.17),
  ('G3_12', 3.511),
  ('F0_22', 0.0),
  ('F2_22', 0.0)],
 'v_soc_n': [0.124],
 'c_soc': 13.4977,
 'edge_ene': [932.7],
 'gamma_c': [0.3]}
```

**Comment by shenmidelin** [comment]
@mpmdean Yes, you are right. In my local computer, I indeed added 3d10_2p5, somehow, I forgot to update them to the main repo.

**Pull request merged**
