### PR TITLE
add ffmpeg to docker_interactive

### PR DESCRIPTION
**Pull request by mpmdean**
ffmpeg is needed for matplotlib animations and is now included in dockerfile_interactive.

### CODE REVIEW

**Comment by mpmdean** [comment]
Merging since this does not touch the edrixs source code.

**Comment by mrakitin** [comment]
We have `ffmpeg` in conda. Should the recipe of `edrixs` include that dependency too? We deploy `ffmpeg` on the floor anyway now, but if it's used by the package, it would be nice to list it explicitly.

**Comment by mpmdean** [comment]
`ffmpeg` is not needed for any of the source code. I'm including it as a convenience for those who want to use the bigger rather than the minimal docker image. 

By the way. I have some confusion about our docker build. The dockerfile_intereactive builds locally just fine, but I got a build failure when I merged, but if I just retrigger what should(?) be an identical build it works fine.
https://hub.docker.com/repository/docker/edrixs/edrixs_interactive/timeline

**Comment by mrakitin** [comment]
There is this error in the failed build:
```
ValueError: Invalid file object: <_io.TextIOWrapper name=6 encoding='ANSI_X3.4-1968'>
```
Not sure why it happened - network issues?

**Pull request merged**
