### PR TITLE
DEV: Add code scanning

### PR DESCRIPTION
**Pull request by stuartcampbell**
Turning on code scanning

### CODE REVIEW

**Comment by mpmdean** [comment]
Thanks @stuartcampbell 

It's not clear to me why the Travis build is showing as pending.

**Comment by stuartcampbell** [comment]
Yeah, Sorry I am just playing with this code analysis checking stuff... 😄

**Comment by mrakitin** [comment]
I am not sure how to interpret the result of this workflow. @stuartcampbell, do we need it in this repo?

**Comment by mpmdean** [comment]
This PR has been open a while, is this solved by #125  ? I

**Comment by mrakitin** [comment]
Let's close it for now. We already have enough workflows to do code checking.

**Pull request closed without merging**
