### PR TITLE
implement general solvers for single impurity Anderson model

### PR DESCRIPTION
**Pull request by shenmidelin**
Solvers (ed_siam_fort, xas_siam_fort, rixs_siam_fort) for single impurity Anderson model has been implemented.  

1. ed_siam_fort can search the ground state in different total occupancy N and can also do ED for a given total occupancy N.

2. an Anderson impurity example is added in examples/more/RIXS/Ba2YOsO6/  to reproduce the example in examples/cpc/anderson_impurity based on the new solvers.

3. the return values: v_norb, c_norb of ed_1v1c_fort, ed_2v1c_fort are removed for simplicity.

4. python pickle module is used to save the poles objects returned from XAS or RIXS for later plots.

### CODE REVIEW

**Comment by mpmdean** [comment]
If we can organize the format into arrays, I wonder if saving as npz might be preferable to pickle? Pickle doesn't guarantee that you will be able to open the file later?

**Comment by shenmidelin** [comment]
I think pickle is easy and convenient for users. One just loads the data, and call the function 

`poles_dict = pickle.load(pkl_file)`
` get_spectra_from_poles(poles_dict, omega_mesh, gamma_mesh, temperature)`

to return the spectra, so the user do not need to know the details of that dict. 

In that dict format, I only use Python's list and dict types, no Numpy's arrays, so I think the compatibility is not a problem. I also see on [Python's webpage](https://docs.python.org/3/library/pickle.html)

> The pickle serialization format is guaranteed to be backwards compatible across Python releases provided a compatible pickle protocol is chosen and pickling and unpickling code deals with Python 2 to Python 3 type differences if your data is crossing that unique breaking change language boundary.

**Comment by mrakitin** [comment]
Pickled objects may not be compatible when opened in different versions of Python than they were created with (e.g. saved a pickled data with Python 2.7 and opening it with Python 3.6). The npy/npz approach seems to be more reliable in case pure nd-arrays are saved. Better, a language-independent format (HDF5 or Nexus or Protobuf) can be used to allow access to the data with different tools or languages. See https://docs.python-guide.org/scenarios/serialization/ for some hints. Also, see why pickle should not be used here: https://www.benfrederickson.com/dont-pickle-your-data.

**Comment by shenmidelin** [comment]
@mrakitin Thanks a lot for these information! There is no serialization of python objects in the edrixs codes. The only place is in the example folder, so I will let the users to choose their own methods to save those results and I will change the default way as saving a .json file.

**Comment by mrakitin** [comment]
Another point to not to use picked files (`npy` in this case): https://www.bleepingcomputer.com/news/security/numpy-is-awaiting-fix-for-critical-remote-code-execution-bug/.

**Pull request merged**
